### ISSUE TITLE
Run the app through the OWASP security checklist

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#161]
It's a special challenge to find it. There are no defined acceptance criteria for this one, apart from just — _write up in the README whatever you want to say about this experience_. Give a link to the checklist, maybe write some code, idk.

**Comment by illright** [comment]
The closest I could find to the mysterious _OWASP Security Checklist_ is the [OWASP Top Ten Project](https://owasp.org/www-project-top-ten/).

- [ ] [A01:2021-Broken Access Control](https://owasp.org/Top10/A01_2021-Broken_Access_Control/) — **blocked by not knowing how to authenticate in Supabase through Cypress**  
  (https://github.com/supabase/supabase/discussions/6177)
- [x] [A02:2021-Cryptographic Failures](https://owasp.org/Top10/A02_2021-Cryptographic_Failures/)
  - We don't store or manage data ourselves, relying on Supabase and HTTPS to communicate with it
  - We don't host our application ourselves, relying on Cloudflare and HTTPS to server the website
  - We don't generate our own keys for Supabase, relying on their own algorithms to generate strong keys
  - We use GitHub OAuth and store user metadata in an unexposed table in Supabase
- [ ] [A03:2021-Injection](https://owasp.org/Top10/A03_2021-Injection/)
- [x] [A04:2021-Insecure Design](https://owasp.org/Top10/A04_2021-Insecure_Design/)
  - We rely on third-party infrastructure and authentication protocols
- [ ] [A05:2021-Security Misconfiguration](https://owasp.org/Top10/A05_2021-Security_Misconfiguration/)
- [ ] [A06:2021-Vulnerable and Outdated Components](https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/)
- [x] [A07:2021-Identification and Authentication Failures](https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/)
  - GitHub manages authentication for us
- [ ] [A08:2021-Software and Data Integrity Failures](https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/)
- [ ] [A09:2021-Security Logging and Monitoring Failures](https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/)
- [ ] [A10:2021-Server-Side Request Forgery](https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/)
